language: ruby
install: bundle install
script: bundle exec rake site:deploy --quiet
env:
  global:
    secure: DnL+Jp6j8hKqN4w2Kp+kc7KNYIBsC9KZCBndI53D9LTtjr3qfw6wXpdMrxoc/NFhbuaIwt1AjRhYbCMnqp61ZObiG9XRQ7Gt9pw4d/Y0bsGTuV+1ycyDuCTulXeGQyZOtozCCjnlDP6gd4F3SYosEmaMxjYvKkxfg/S4xb8E9o=
