language: ruby
install: bundle install
script: bundle exec rake site:deploy --quiet
env:
  global:
  - secure: piXbwnq9dSgiEXJ6mGkFFQKsS7DShvruYoUJUMDMQBYdeJRj8+oZelbgHJXul3Ewr8SqBGf11n3SPoyjNRXalqn+i5BTkLSyW7Xp2zAB92pIQQ1wtGwVXlfF2w1j8t93T5m8IW09G/ItLwQPrMPe5nqKsQ/FugLiZroUzt1fSL8=
